src/main/java/com/psybergate/finance/domain/Investment.java
package com.psybergate.finance.domain;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Transient;

import com.psybergate.finance.util.MoneyToNumericConverter;

@Entity
public class Investment {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	private Integer customerId;

	private String name;

	@Convert(converter = MoneyToNumericConverter.class)
	private Money principal;

	private Double interestRate;

	private Integer term;

	@Convert(converter = MoneyToNumericConverter.class)
	private Money monthlyContribution;

	@Transient
	private List<InvestmentForecastEntry> forecast;

	@OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
	@JoinColumn(name = "investmentid")
	private List<InvestmentEvent> events;

	public Investment() {
	}

	public Investment(Money principal, Double interestRate, Integer term,
			Money monthlyContribution, List<InvestmentEvent> events) {
		this(null, null, principal, interestRate, term, monthlyContribution,
				events);
	}

	public Investment(Integer customerId, String investmentName, Money principal,
			Double interestRate, Integer term, Money monthlyContribution,
			List<InvestmentEvent> events) {
		if (monthlyContribution == null) {
			monthlyContribution = new Money();
		}
		this.principal = principal;
		this.interestRate = interestRate;
		this.term = term;
		this.monthlyContribution = monthlyContribution;
		this.events = events;
		generateEntries();
	}

	private void addInvestmentForecastEntry(InvestmentForecastEntry entry) {
		forecast.add(entry);
	}

	public Money getFutureValue() {
		if (forecast == null || forecast.isEmpty()) {
			return new Money();
		}
		InvestmentForecastEntry lastInvestmentForecastEntry = forecast
				.get(forecast.size() - 1);
		return lastInvestmentForecastEntry.getClosingBalance();
	}

	public Money getTotalInterest() {
		return getFutureValue().subtract(getTotalContribution());
	}

	public List<InvestmentForecastEntry> getForecast() {
		return forecast;
	}

	public Money getPrincipal() {
		return principal;
	}

	public void generateEntries() {
		setForecast(new ArrayList<>());
		if (term == null || term < 1 || interestRate == null || principal == null)
			return;
		InvestmentForecastEntry firstEntry = new InvestmentForecastEntry(1,
				interestRate, principal, monthlyContribution, new Money());
		handleEvents(firstEntry);
		addInvestmentForecastEntry(firstEntry);
		for (Integer month = 2; month <= getTerm(); month++) {
			InvestmentForecastEntry prevEntry = getForecast().get(month - 2);
			InvestmentForecastEntry entry = prevEntry.generateNextEntry();
			handleEvents(entry);
			addInvestmentForecastEntry(entry);
		}
	}

	private void handleEvents(InvestmentForecastEntry entry) {
		Integer month = entry.getMonth();
		InvestmentEvent event = getEvent(month);
		entry.applyEvent(event);
	}

	public InvestmentEvent getEvent(Integer month) {
		if (month == null) {
			return null;
		}
		for (InvestmentEvent event : getEvents()) {
			if (month == event.getMonth()) {
				return event;
			}
		}
		return null;
	}

	public void setPrincipal(Money principal) {
		this.principal = principal;
	}

	public Double getInterestRate() {
		return interestRate;
	}

	public void setInterestRate(Double interestRate) {
		this.interestRate = interestRate;
	}

	public Integer getTerm() {
		return term;
	}

	public void setTerm(Integer term) {
		this.term = term;
	}

	public Money getMonthlyContribution() {
		return monthlyContribution;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setMonthlyContribution(Money monthlyContribution) {
		if (monthlyContribution == null) {
			monthlyContribution = new Money();
		}
		this.monthlyContribution = monthlyContribution;
	}

	private void setForecast(List<InvestmentForecastEntry> forecast) {
		this.forecast = forecast;
	}

	public List<InvestmentEvent> getEvents() {
		return events;
	}

	public void setEvents(List<InvestmentEvent> events) {
		this.events = events;
		generateEntries();
	}

	public boolean hasEvents() {
		return events != null && !events.isEmpty();
	}

	public Integer getCustomerId() {
		return customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public Money getClosingBalance() {
		return getFutureValue();
	}

	public Money getTotalContribution() {
		Money totalCapital = principal;
		for (InvestmentForecastEntry entry : forecast) {
			totalCapital = totalCapital.add(entry.getTotalContribution());
		}
		return totalCapital;
	}

	@Override
	public String toString() {
		return "Investment [id=" + id + ", customerId=" + customerId + ", name="
				+ name + ", principal=" + principal + ", interestRate="
				+ interestRate + ", term=" + term + ", monthlyContribution="
				+ monthlyContribution + ", events=" + events + "]";
	}

}

src/main/java/com/psybergate/finance/view/model/EventViewModel.java
package com.psybergate.finance.view.model;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

import com.psybergate.finance.domain.Money;

@RequestScoped
@Named
public class EventViewModel {

	private static String[] TRANSACTION_OPTIONS = {"Withdraw", "Deposit"};

	private Integer month;

	private Double interestRate;

	private Money monthlyAmount;

	private Money amount;

	private boolean valid = true;

	private String transactionType;

	public Integer getMonth() {
		return month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	public Double getInterestRate() {
		return interestRate;
	}

	public void setInterestRate(Double interestRate) {
		this.interestRate = interestRate;
	}

	public Money getMonthlyAmount() {
		return monthlyAmount;
	}

	public void setMonthlyAmount(Money monthlyAmount) {
		this.monthlyAmount = monthlyAmount;
	}

	public Money getAmount() {
		return amount;
	}

	public void setAmount(Money amount) {
		this.amount = amount;
	}

	public boolean isValid() {
		return valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	public String getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public String[] getTransactionOptions() {
		return TRANSACTION_OPTIONS;
	}

}

src/main/java/com/psybergate/finance/view/model/InvestmentViewModel.java
package com.psybergate.finance.view.model;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.inject.spi.CDI;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

import com.psybergate.finance.domain.InvestmentForecastEntry;
import com.psybergate.finance.domain.Money;
import com.psybergate.finance.util.PrintUtil;

@ViewScoped
@Named
public class InvestmentViewModel implements Serializable {

	private static final long serialVersionUID = 2605546133147882749L;

	private Integer id;

	private String name;

	private Money principal;

	private Integer term;

	private Double interestRate;

	private Money monthlyContribution;

	private Money closingBalance;

	private Money futureValue;

	private Money totalInterest;

	private Money totalContribution;

	private List<EventViewModel> events;

	private List<InvestmentForecastEntry> forecast;

	public InvestmentViewModel() {
		InvestmentDataViewModel data = CDI.current()
				.select(InvestmentDataViewModel.class).get();
		setId(data.getId());
		setPrincipal(data.getPrincipal());
		setTerm(data.getTerm());
		setInterestRate(data.getInterestRate());
		setMonthlyContribution(data.getMonthlyContribution());
		setEvents(data.getEvents());
		PrintUtil.print("investment data: " + data);
	}

	public Money getTotalContribution() {
		return totalContribution;
	}

	public void setTotalContribution(Money totalContribution) {
		this.totalContribution = totalContribution;
	}

	public Money getTotalInterest() {
		return totalInterest;
	}

	public void setTotalInterest(Money totalInterest) {
		this.totalInterest = totalInterest;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Money getPrincipal() {
		return principal;
	}

	public void setPrincipal(Money principal) {
		this.principal = principal;
	}

	public Integer getTerm() {
		return term;
	}

	public void setTerm(Integer term) {
		this.term = term;
	}

	public Double getInterestRate() {
		return interestRate;
	}

	public void setInterestRate(Double interestRate) {
		this.interestRate = interestRate;
	}

	public Money getMonthlyContribution() {
		return monthlyContribution;
	}

	public void setMonthlyContribution(Money monthlyContribution) {
		this.monthlyContribution = monthlyContribution;
	}

	public Money getClosingBalance() {
		return closingBalance;
	}

	public void setClosingBalance(Money closingBalance) {
		this.closingBalance = closingBalance;
	}

	public Money getFutureValue() {
		return futureValue;
	}

	public void setFutureValue(Money futureValue) {
		this.futureValue = futureValue;
	}

	public List<EventViewModel> getEvents() {
		return events;
	}

	public void setEvents(List<EventViewModel> events) {
		this.events = events;
	}

	public List<InvestmentForecastEntry> getForecast() {
		return forecast;
	}

	public void setForecast(List<InvestmentForecastEntry> forecast) {
		this.forecast = forecast;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return "InvestmentViewModel [id=" + id + ", name=" + name + ", principal="
				+ principal + ", term=" + term + ", interestRate=" + interestRate
				+ ", monthlyContribution=" + monthlyContribution
				+ ", closingBalance=" + closingBalance + ", futureValue="
				+ futureValue + ", totalInterest=" + totalInterest
				+ ", totalContribution=" + totalContribution + ", events=" + events
				+ "]";
	}

}

src/main/java/com/psybergate/finance/controller/InvestmentController.java
package com.psybergate.finance.controller;

import java.math.BigDecimal;
import java.math.RoundingMode;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.spi.CDI;
import javax.inject.Inject;
import javax.inject.Named;

import com.psybergate.finance.controller.dispatcher.PageDispatcher;
import com.psybergate.finance.domain.Customer;
import com.psybergate.finance.domain.Investment;
import com.psybergate.finance.domain.InvestmentEvent;
import com.psybergate.finance.domain.Money;
import com.psybergate.finance.exception.ValidationException;
import com.psybergate.finance.interfaces.CustomerService;
import com.psybergate.finance.interfaces.InvestmentService;
import com.psybergate.finance.util.PrintUtil;
import com.psybergate.finance.util.ViewModelConverter;
import com.psybergate.finance.view.model.CustomerViewModel;
import com.psybergate.finance.view.model.EventViewModel;
import com.psybergate.finance.view.model.InvestmentDataViewModel;
import com.psybergate.finance.view.model.InvestmentViewModel;
import com.psybergate.web.view.forecast.investment.InvestmentLineVisualisation;

@ApplicationScoped
@Named("investmentController")
public class InvestmentController extends FinancialProductController {

	private static final String EVENT_FORM = "tabView:investmentEventForm";

	private static final String INVESTMENT_FORM = "investmentForm";

	@Inject
	private InvestmentService investmentService;

	@Inject
	private CustomerService customerService;

	private PageDispatcher pageDispatcher = new PageDispatcher();

	public InvestmentController() {
	}

	public void generateForecast(InvestmentViewModel investmentViewModel) {
		Investment investment = ViewModelConverter
				.toInvestment(investmentViewModel);
		try {
			investmentService.validateInvestment(investment, false);
		} catch (ValidationException e) {
			PrintUtil.print("error messages: " + e.getErrorMessages());
			renderErrorMessages(INVESTMENT_FORM, e.getErrorMessages());
			return;
		}
		investmentViewModel
				.setMonthlyContribution(investment.getMonthlyContribution());
		investmentViewModel
				.setTotalContribution(investment.getTotalContribution());
		investmentViewModel.setTotalInterest(investment.getTotalInterest());
		investmentViewModel.setClosingBalance(investment.getClosingBalance());
		investmentViewModel.setFutureValue(investment.getFutureValue());
		investmentViewModel.setForecast(investment.getForecast());
	}

	public String showForecast(InvestmentDataViewModel investmentData) {
		Investment investment = ViewModelConverter.toInvestment(investmentData);
		try {
			investmentService.validateInvestment(investment, false);
			return pageDispatcher.getPage("investmentForecast");
		} catch (ValidationException e) {
			renderErrorMessages(INVESTMENT_FORM, e.getErrorMessages());
			return null;
		}
	}

	public void addEvent(InvestmentViewModel investmentViewModel,
			EventViewModel eventViewModel) {
		PrintUtil.print("investmentViewModel: " + investmentViewModel);
		Investment investment = ViewModelConverter
				.toInvestment(investmentViewModel);
		PrintUtil.print("investment: " + investment);
		InvestmentEvent event = ViewModelConverter
				.toInvestmentEvent(eventViewModel);
		try {
			if (event.additionalAmountChanged() || event.interestRateChanged()
					|| event.monthlyAmountChanged()) {
				investmentService.validateEvent(investment, event);
				if (investment.getId() != null) {
					investmentService.addEvent(investment, event);
				}
				investmentViewModel.getEvents().add(eventViewModel);
			}
		} catch (ValidationException e) {
			eventViewModel.setValid(false);
			renderErrorMessages(EVENT_FORM, e.getErrorMessages());
		}
	}

	public Investment getInvestment(InvestmentDataViewModel investmentData) {
		return ViewModelConverter.toInvestment(investmentData);
	}

	public Investment getInvestment(InvestmentViewModel investmentViewModel) {
		return ViewModelConverter.toInvestment(investmentViewModel);
	}

	public boolean isEmpty(InvestmentDataViewModel investmentData) {
		return (investmentData.getTerm() == null
				&& investmentData.getPrincipal() == null
				&& investmentData.getMonthlyContribution() == null
				&& investmentData.getInterestRate() == null
				&& investmentData.getEvents() == null);
	}

	public String saveInvestment(InvestmentViewModel investmentViewModel,
			CustomerViewModel customerViewModel) {
		Customer customer = customerService
				.getCustomer(customerViewModel.getCustomerNum());

		if (customer == null) {
			customer = new Customer(customerViewModel.getCustomerNum(),
					customerViewModel.getName());
			customerService.addCustomer(customer);
			PrintUtil.print("saved: " + customer);
		}
		else {
			PrintUtil.print("customer already exists: " + customer);
		}
		Investment investment = ViewModelConverter
				.toInvestment(investmentViewModel);
		investment.setCustomerId(customer.getId());
		investmentService.saveInvestment(investment);
		investmentViewModel.setId(investment.getId());
		return null;
	}

	public String someMethod() {
		try {
			InvestmentViewModel investmentViewModel = getCurrentCDIInstance(
					InvestmentViewModel.class);
			InvestmentLineVisualisation lineVisual = getCurrentCDIInstance(
					InvestmentLineVisualisation.class);
			BigDecimal closingBalance = investmentViewModel.getClosingBalance()
					.getAmount();
			BigDecimal principalAmount = investmentViewModel.getPrincipal()
					.getAmount();
			BigDecimal principalTermAsBigDecimal = lineVisual
					.getPrincipalTermAsBigDecimal(investmentViewModel);
			String result = "".concat(closingBalance.subtract(principalAmount)
					.divide(principalTermAsBigDecimal, 2, RoundingMode.HALF_UP)
					.toString());
			return result;
		} catch (Exception e) {
			return "2500.00";
		}
	}

	public String someMethod2() {
		InvestmentViewModel investmentViewModel = CDI.current()
				.select(InvestmentViewModel.class).get();
		Money principal = investmentViewModel.getPrincipal();
		Money closingBalance = investmentViewModel.getClosingBalance();
		try {
			return closingBalance.subtract(principal).getAmount().toString();
		} catch (Exception e) {
			return "2500.00";
		}
	}
}

src/main/webapp/faces/dependencies/investment/dialogs/event-dialog.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition>

	<p:dialog header="Event" widgetVar="events-dialogue" minHeight="40"
		visible="#{!eventViewModel.valid}" closeOnEscape="true">
		<h:form id="investmentEventForm">
			<p:inputNumber id="event" rendered="false"></p:inputNumber>
			<p:message for="event" />
			<p:panelGrid columns="2">
				<b>Month: </b>
				<h:panelGroup>
					<div>
						<p:inputNumber id="month" value="#{eventViewModel.month}"
							minValue="0" decimalPlaces="0" />
						<div>
							<p:message for="month" />
						</div>
					</div>
				</h:panelGroup>

				<b>Change Monthly Contribution: </b>
				<h:panelGroup>
					<div>
						<p:inputNumber id="monthlyAmount"
							value="#{eventViewModel.monthlyAmount}" minValue="0">
							<f:converter
								converterId="com.psybergate.web.converter.MoneyConverter" />
						</p:inputNumber>
						<div>
							<p:message for="monthlyAmount" />
						</div>
					</div>
				</h:panelGroup>

				<b>Change Interest Rate: </b>
				<h:panelGroup>
					<div>
						<p:inputNumber id="interestRate"
							value="#{eventViewModel.interestRate}" minValue="0" />
						<div>
							<p:message for="interestRate" />
						</div>
					</div>
				</h:panelGroup>
				<b>Additional Transaction: </b>
				<h:panelGroup>
					<div>
						<p:selectOneMenu id="transactionType"
							value="#{eventViewModel.transactionType}">
							<f:selectItems value="#{eventViewModel.transactionOptions}" />
						</p:selectOneMenu>
						<p:inputNumber id="amount" value="#{eventViewModel.amount}"
							minValue="0">
							<f:converter
								converterId="com.psybergate.web.converter.MoneyConverter" />
						</p:inputNumber>
						<div>
							<p:message for="amount" />
						</div>
					</div>
				</h:panelGroup>
			</p:panelGrid>
			<hr />
			<p:commandButton value="Add" ajax="false"
				action="#{investmentController.addEvent(investmentViewModel, eventViewModel)}">
			</p:commandButton>
		</h:form>
	</p:dialog>

</ui:composition>
</html>

src/main/webapp/faces/dependencies/investment/dialogs/save-forecast-dialog.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition>
	<p:dialog header="Save Forecast" widgetVar="save-dialogue"
		minHeight="40" closeOnEscape="true">
		<h:form>
			<p:panelGrid columns="2">
				<b>Customer Number: </b>
				<h:panelGroup>
					<div>
						<p:inputNumber id="customerNum"
							value="#{customerViewModel.customerNum}" decimalPlaces="0" />
						<p:message for="customerNum" />
					</div>
				</h:panelGroup>

				<b>Customer Name: </b>
				<h:panelGroup>
					<div>
						<h:inputText id="customerName" value="#{customerViewModel.name}" />
						<p:message for="customerName" />
					</div>
				</h:panelGroup>

				<b>Forecast Name: </b>
				<h:panelGroup>
					<div>
						<h:inputText id="investmentName"
							value="#{investmentViewModel.name}" />
						<p:message for="investmentName" />
					</div>
				</h:panelGroup>

			</p:panelGrid>
			<hr />
			<p:commandButton value="Save Forecast" ajax="false"
				action="#{investmentController.saveInvestment(investmentViewModel, customerViewModel)}">
			</p:commandButton>
		</h:form>
	</p:dialog>
</ui:composition>
</html>

src/main/webapp/faces/dependencies/investment/dialogs/summary-dialog.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition>
	<h:form id="investments"
		action="/faces/dependencies/investment/forecast">
		<p:dataTable id="available-investments" var="investmentRecord"
			value="#{investmentController.getListOfInvestments(customerViewModel.customerNum)}"
			scrollable="true" resizableColumns="true" scrollHeight="512"
			style="font-size:1.15em; border: 1pt solid #d4d4d4;">

			<f:facet name="header">
				<h:outputText value="List of Available Investments" />
			</f:facet>

			<p:column headerText="Investment Name">
				<div style="text-align: right;">
					<h:outputText value="#{investmentRecord.investmentName}" />
				</div>
			</p:column>

			<p:column headerText="Principal">
				<div style="text-align: right;">
					<h:outputText value="#{investmentRecord.principal}" />
					<br />
				</div>
			</p:column>

			<p:column headerText="Interest Rate">
				<div style="text-align: right;">
					<h:outputText value="#{investmentRecord.interestRate}" />
				</div>
			</p:column>

			<p:column headerText="Monthly Contribution">
				<div style="text-align: right;">
					<h:outputText value="#{investmentRecord.monthlyContribution}" />
				</div>
			</p:column>

			<p:column headerText="Term">
				<div style="text-align: right;">
					<h:outputText value="#{investmentRecord.term}" />
				</div>
			</p:column>

			<p:column headerText="Choose Forecast">

				<div style="text-align: center;">
					<p:commandButton value="Show Forecast" ajax="false"
						action="#{investmentController.showForecast(investmentData)}"
						onclick="alert('#{investmentRecord.id}')">
					</p:commandButton>
					<!-- 
							action="/faces/dependencies/investment/forecast?redirect=true" />
							-->
				</div>

			</p:column>

		</p:dataTable>
	</h:form>
</ui:composition>
</html>